//#region imports
import * as os from 'os'; // @backend

import {
  APP_INITIALIZER,
  ApplicationConfig,
  provideBrowserGlobalErrorListeners,
  isDevMode,
  mergeApplicationConfig,
  provideZonelessChangeDetection,
  signal,
} from '@angular/core'; // @browser
import { Component } from '@angular/core'; // @browser
import { OnInit } from '@angular/core'; // @browser
import {
  provideClientHydration,
  withEventReplay,
} from '@angular/platform-browser';
import {
  provideRouter,
  RouterModule,
  Routes,
  withHashLocation,
} from '@angular/router';
import { provideServiceWorker } from '@angular/service-worker';
import { provideServerRendering, withRoutes } from '@angular/ssr';
import { RenderMode, ServerRoute } from '@angular/ssr';
import Aura from '@primeng/themes/aura'; // @browser
import { providePrimeNG } from 'primeng/config'; // @browser
import { Taon, TAON_CONTEXT, TaonContext } from 'taon/src';

import { HOST_CONFIG } from './app.hosts';
import { ENV_ANGULAR_NODE_APP_BUILD_PWA_DISABLE_SERVICE_WORKER } from './lib/env/env.angular-node-app';
// @placeholder-for-imports
//#endregion

//#region constants
const firstHostConfig = (Object.values(HOST_CONFIG) || [])[0];
console.log('Your backend host ' + firstHostConfig?.host);
console.log('Your frontend host ' + firstHostConfig?.frontendHost);
//#endregion

//#region my-entity component
//#region @browser
@Component({
  selector: 'app-root',

  imports: [RouterModule],
  template: `<router-outlet /> `,
})
export class MyEntityApp implements OnInit {
  itemsLoaded = signal(false);

  ngOnInit(): void {
    Taon.removeLoader().then(() => {
      this.itemsLoaded.set(true);
    });
  }
}
//#endregion

//#endregion

//#region my-entity routes
//#region @browser
export const MyEntityServerRoutes: ServerRoute[] = [
  {
    path: '**',
    renderMode: RenderMode.Prerender,
  },
];
export const MyEntityClientRoutes: Routes = [
  {
    path: '',
    pathMatch: 'full',
    redirectTo: () => {
      if (MyEntityClientRoutes.length === 1) {
        return '';
      }
      return MyEntityClientRoutes.find(r => r.path !== '')!.path!;
    },
  },
  // PUT ALL ROUTES HERE
  // @placeholder-for-routes
];
//#endregion
//#endregion

//#region my-entity app configs
//#region @browser
export const MyEntityAppConfig: ApplicationConfig = {
  providers: [
    provideZonelessChangeDetection(),
    providePrimeNG({
      theme: {
        preset: Aura,
      },
    }),
    {
      provide: APP_INITIALIZER,
      multi: true,
      useFactory: () => MyEntityStartFunction,
    },
    provideBrowserGlobalErrorListeners(),
    // remove withHashLocation() to use SSR
    provideRouter(MyEntityClientRoutes, withHashLocation()),
    provideClientHydration(withEventReplay()),
    provideServiceWorker('ngsw-worker.js', {
      enabled:
        !isDevMode() && !ENV_ANGULAR_NODE_APP_BUILD_PWA_DISABLE_SERVICE_WORKER,
      registrationStrategy: 'registerWhenStable:30000',
    }),
  ],
};

export const MyEntityServerConfig: ApplicationConfig = {
  providers: [provideServerRendering(withRoutes(MyEntityServerRoutes))],
};

export const MyEntityConfig = mergeApplicationConfig(
  MyEntityAppConfig,
  MyEntityServerConfig,
);
//#endregion
//#endregion

//#region my-entity context
var MyEntityContext = Taon.createContext(() => ({
  ...HOST_CONFIG['MyEntityContext'],
  contexts: { },
  disabledRealtime: true,
}));
//#endregion

//#region my-entity start function
export const MyEntityStartFunction = async (
  startParams?: Taon.StartParams,
): Promise<void> => {
  await MyEntityContext.initialize()

  //#region initialize auto generated active contexts
  const autoGeneratedActiveContextsForApp: TaonContext[] = [
    // @placeholder-for-contexts-init
  ];

  const priorityContexts = [
    // put here manual priority for contexts if needed
  ];

  const activeContextsForApp: TaonContext[] = [
    ...priorityContexts,
    ...autoGeneratedActiveContextsForApp.filter(
      c => !priorityContexts.includes(c),
    ),
  ];

  for (const activeContext of activeContextsForApp) {
    await activeContext.initialize();
  }
  //#endregion

  //#region @backend
  if (
    startParams?.onlyMigrationRun ||
    startParams?.onlyMigrationRevertToTimestamp
  ) {
    process.exit(0);
  }
  //#endregion

  //#region @backend
  console.log(`Hello in NodeJs backend! os=${os.platform()}`);
  //#endregion
};
//#endregion

//#region default export
export default MyEntityStartFunction;
//#endregion
