// THIS FILE IS GENERATED BYT TAON - DO NOT MODIFY
import { createWorkerAdapter } from 'taon/src';
// @ts-ignore
import { app } from '../../../../../../src/app.cloudflare';

export default {
  fetch: createWorkerAdapter(app),
};
// THIS FILE IS GENERATED BYT TAON - DO NOT MODIFY
