// THIS FILE IS GENERATED BYT TAON - DO NOT MODIFY
import { isEqual } from 'lodash-es';

//#region cors headers
function corsHeaders() {
  return {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type, Authorization',
  };
}
//#endregion

export default {
  async fetch(request: Request, env: any): Promise<Response> {
    const url = new URL(request.url);

    //#region handle options
    if (request.method === 'OPTIONS') {
      return new Response(null, { headers: corsHeaders() });
    }
    //#endregion

    //#region ---------- YOUTUBE PLAYLIST VIDEOS ----------
    if (url.pathname === '/youtube-playlist-videos') {
      if (request.method !== 'GET') {
        return new Response('Method Not Allowed', {
          status: 405,
          headers: corsHeaders(),
        });
      }

      return new Response(
        JSON.stringify({
          helloWorod: 'Dariusz',
        }),
        {
          status: 200,
          headers: {
            'Content-Type': 'application/json',
            ...corsHeaders(),
          },
        },
      );
    }
    //#endregion

    return new Response('Not Found', {
      status: 404,
      headers: corsHeaders(),
    });
  },
};
// THIS FILE IS GENERATED BYT TAON - DO NOT MODIFY
