// THIS FILE IS GENERATED BYT TAON - DO NOT MODIFY
import { isEqual } from 'lodash-es';
import { TaonYtCloudFlareWorker } from '@taon-dev/api-workers/src';

//#region cors headers
function corsHeaders() {
  return {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type, Authorization',
  };
}
//#endregion

export default {
  async fetch(request: Request, env: any): Promise<Response> {
    const url = new URL(request.url);

    //#region handle options
    if (request.method === 'OPTIONS') {
      return new Response(null, { headers: corsHeaders() });
    }
    //#endregion

    //#region ---------- YOUTUBE PLAYLIST VIDEOS ----------
    if (url.pathname === '/youtube-playlist-videos') {
      if (request.method !== 'GET') {
        return new Response('Method Not Allowed', {
          status: 405,
          headers: corsHeaders(),
        });
      }

      try {
        const playlistId = url.searchParams.get('playlistId') || '';

        if (!playlistId) {
          return new Response(
            JSON.stringify({
              error: 'Missing playlistId',
            }),
            {
              status: 400,
              headers: {
                'Content-Type': 'application/json',
                ...corsHeaders(),
              },
            },
          );
        }

        let existingPlaylist: TaonYtCloudFlareWorker.YtPlaylistVideo[] = [];
        try {
          const data = await env.KV_DATABASE_ONLINE_NAME.get(playlistId);
          existingPlaylist = (
            data ? JSON.parse(data) : []
          ) as TaonYtCloudFlareWorker.YtPlaylistVideo[];
        } catch (error) {}

        let videos: TaonYtCloudFlareWorker.YtPlaylistVideo[] = [];

        try {
          videos = await TaonYtCloudFlareWorker.getYoutubePlaylistVideos(
            playlistId,
            {
              apiKey: env.YOUTUBE_API_KEY,
            },
          );
          const newIds = videos.map(c => c.videoId).sort();
          const existedIds = existingPlaylist.map(c => c.videoId).sort();
          if (!isEqual(newIds, existedIds)) {
            await env.KV_DATABASE_ONLINE_NAME.put(
              playlistId,
              JSON.stringify(videos),
            );
          }
        } catch (error) {
          videos = existingPlaylist;
        }

        return new Response(JSON.stringify(videos), {
          headers: {
            'Content-Type': 'application/json',
            'Cache-Control': 'public, max-age=60',
            ...corsHeaders(),
          },
        });
      } catch (err) {
        return new Response(
          JSON.stringify({
            error: (err as Error).message,
          }),
          {
            status: 500,
            headers: {
              'Content-Type': 'application/json',
              ...corsHeaders(),
            },
          },
        );
      }
    }
    //#endregion

    return new Response('Not Found', {
      status: 404,
      headers: corsHeaders(),
    });
  },
};
// THIS FILE IS GENERATED BYT TAON - DO NOT MODIFY
