// THIS FILE IS GENERATED BYT TAON - DO NOT MODIFY

//#region cors headers
function corsHeaders() {
	return {
		'Access-Control-Allow-Origin': '*',
		'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
		'Access-Control-Allow-Headers': 'Content-Type, Authorization',
	};
}
//#endregion

//#region youtube playlist helpers
type YtPlaylistVideo = {
	videoId: string;
	title: string;
	url: string;
	thumbnail: string;
	order: number;
};

function extractPlaylistId(input: string): string {
	const raw = (input || '').trim();

	if (!raw) {
		return '';
	}

	if (raw.startsWith('http://') || raw.startsWith('https://')) {
		try {
			const u = new URL(raw);
			return (u.searchParams.get('list') || '').trim();
		} catch {}
	}

	return raw.split('&')[0].trim();
}

function decodeYoutubeText(text: string): string {
	return (text || '')
		.replace(/\\u0026/g, '&')
		.replace(/\\u003d/g, '=')
		.replace(/\\u002F/g, '/')
		.replace(/\\"/g, '"')
		.replace(/\\\\/g, '\\');
}

function getTextFromRuns(obj: any): string {
	if (!obj) {
		return '';
	}

	if (typeof obj?.simpleText === 'string') {
		return obj.simpleText;
	}

	if (Array.isArray(obj?.runs)) {
		return obj.runs
			.map((r: any) => r?.text || '')
			.join('')
			.trim();
	}

	return '';
}

function collectPlaylistVideoRenderers(node: any, out: any[] = []): any[] {
	if (!node || typeof node !== 'object') {
		return out;
	}

	if (node.playlistVideoRenderer) {
		out.push(node.playlistVideoRenderer);
	}

	if (Array.isArray(node)) {
		for (const item of node) {
			collectPlaylistVideoRenderers(item, out);
		}
		return out;
	}

	for (const value of Object.values(node)) {
		collectPlaylistVideoRenderers(value, out);
	}

	return out;
}

async function getYoutubePlaylistVideos(playlistIdOrUrl: string): Promise<YtPlaylistVideo[]> {
	const playlistId = extractPlaylistId(playlistIdOrUrl);

	if (!playlistId) {
		throw new Error('Missing playlistId');
	}

	const ytUrl = `https://www.youtube.com/playlist?list=${encodeURIComponent(playlistId)}`;

	const resp = await fetch(ytUrl, {
		headers: {
			'accept-language': 'en-US,en;q=0.9',
			'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
		},
	});

	if (!resp.ok) {
		throw new Error(`YouTube request failed: ${resp.status} ${resp.statusText}`);
	}

	const html = await resp.text();

	const initialDataMatch = html.match(/var ytInitialData = (\{[\s\S]*?\});<\/script>/);

	if (!initialDataMatch?.[1]) {
		throw new Error('Unable to extract ytInitialData from playlist page');
	}

	let initialData: any;
	try {
		initialData = JSON.parse(initialDataMatch[1]);
	} catch (error) {
		throw new Error('Unable to parse ytInitialData JSON');
	}

	const renderers = collectPlaylistVideoRenderers(initialData);
	const seen = new Set<string>();

	const videos = renderers
		.map((item: any, index: number) => {
			const videoId = item?.videoId || '';
			const title = decodeYoutubeText(getTextFromRuns(item?.title));
			const playlistIndexText = item?.index?.simpleText || item?.indexText?.simpleText || String(index + 1);

			const order = Number(playlistIndexText) || index + 1;

			return {
				videoId,
				title,
				url: `https://www.youtube.com/watch?v=${videoId}`,
				thumbnail: `https://img.youtube.com/vi/${videoId}/hqdefault.jpg`,
				order,
			};
		})
		.filter((item) => {
			if (!item.videoId || !item.title || seen.has(item.videoId)) {
				return false;
			}
			seen.add(item.videoId);
			return true;
		})
		.sort((a, b) => a.order - b.order);

	return videos;
}
//#endregion

export default {
	async fetch(request: Request, env: any): Promise<Response> {
		const url = new URL(request.url);

		//#region handle options
		if (request.method === 'OPTIONS') {
			return new Response(null, { headers: corsHeaders() });
		}
		//#endregion

		/**
		 * By default worker is developemnt mode (WORKER_STRIP_MODE === undefined)
		 * In production mode WORKER_STRIP_MODE === 'production'.
		 */
		const isProdMode = env.WORKER_STRIPE_MODE === 'production';

		//#region ---------- Hello WORLD ----------
		if (!isProdMode && url.pathname === '/') {
			return new Response('Hello world!');
		}
		//#endregion

		//#region ---------- YOUTUBE PLAYLIST VIDEOS ----------
		if (url.pathname === '/youtube-playlist-videos') {
			if (request.method !== 'GET') {
				return new Response('Method Not Allowed', {
					status: 405,
					headers: corsHeaders(),
				});
			}

			try {
				const playlistId = url.searchParams.get('playlistId') || '';

				if (!playlistId) {
					return new Response(
						JSON.stringify({
							error: 'Missing playlistId',
						}),
						{
							status: 400,
							headers: {
								'Content-Type': 'application/json',
								...corsHeaders(),
							},
						},
					);
				}

				const videos = await getYoutubePlaylistVideos(playlistId);

				return new Response(JSON.stringify(videos), {
					headers: {
						'Content-Type': 'application/json',
						...corsHeaders(),
					},
				});
			} catch (err) {
				return new Response(
					JSON.stringify({
						error: (err as Error).message,
					}),
					{
						status: 500,
						headers: {
							'Content-Type': 'application/json',
							...corsHeaders(),
						},
					},
				);
			}
		}
		//#endregion

		return new Response('Not Found', {
			status: 404,
			headers: corsHeaders(),
		});
	},
};
// THIS FILE IS GENERATED BYT TAON - DO NOT MODIFY
