// THIS FILE IS GENERATED BYT TAON - DO NOT MODIFY
import Stripe from 'stripe';
import type { TaonStripeCloudflareWorkerData } from 'tnp-core/src';

//#region save to db client data
const saveToDb = async (env: any, productId: string, clientEmail: string, stripeSessionId: string) => {
	clientEmail = (clientEmail || '').toLowerCase().trim();
	const purchaseKey = `purchase:${clientEmail}:${productId}`;
	const saleKey = `sale:${stripeSessionId}`;

	// prevent duplicate purchase
	const existingSale = await env.KV_DATABASE_ONLINE_NAME.get(saleKey);

	if (existingSale) {
		return new Response('Event already processed');
	}

	const data = {
		productId,
		clientEmail,
		stripeSessionId,
		createdAt: new Date().toISOString(),
	};

	await env.KV_DATABASE_ONLINE_NAME.put(saleKey, JSON.stringify(data));
	await env.KV_DATABASE_ONLINE_NAME.put(purchaseKey, stripeSessionId);

	return new Response('OK');
};
//#endregion

//#region cors headers
function corsHeaders() {
	return {
		'Access-Control-Allow-Origin': '*',
		'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
		'Access-Control-Allow-Headers': 'Content-Type, Authorization',
	};
}
//#endregion

//#region youtube playlist helpers
type YtPlaylistVideo = {
	videoId: string;
	title: string;
	url: string;
	thumbnail: string;
	order: number;
};

function decodeYoutubeText(text: string): string {
	return text
		.replace(/\\u0026/g, '&')
		.replace(/\\u003d/g, '=')
		.replace(/\\u002F/g, '/')
		.replace(/\\"/g, '"')
		.replace(/\\\\/g, '\\');
}

async function getYoutubePlaylistVideos(playlistIdOrUrl: string): Promise<YtPlaylistVideo[]> {
	const playlistId = (() => {
		const raw = (playlistIdOrUrl || '').trim();

		if (!raw) {
			return '';
		}

		if (raw.startsWith('http://') || raw.startsWith('https://')) {
			try {
				const u = new URL(raw);
				return (u.searchParams.get('list') || '').trim();
			} catch {}
		}

		return raw.split('&')[0].trim();
	})();

	if (!playlistId) {
		throw new Error('Missing playlistId');
	}

	const ytUrl = `https://www.youtube.com/playlist?list=${encodeURIComponent(playlistId)}`;

	const resp = await fetch(ytUrl, {
		headers: {
			'accept-language': 'en-US,en;q=0.9',
			'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
		},
	});

	if (!resp.ok) {
		throw new Error(`YouTube request failed: ${resp.status} ${resp.statusText}`);
	}

	const html = await resp.text();

	const matches = [...html.matchAll(/"videoId":"([a-zA-Z0-9_-]{11})".+?"title":\{"runs":\[\{"text":"(.*?)"\}\]/g)];

	const seen = new Set<string>();

	return matches
		.map((m, index) => {
			const videoId = m[1];
			const title = decodeYoutubeText(m[2] || '').trim();

			return {
				videoId,
				title,
				url: `https://www.youtube.com/watch?v=${videoId}`,
				thumbnail: `https://img.youtube.com/vi/${videoId}/hqdefault.jpg`,
				order: index + 1,
			};
		})
		.filter((item) => {
			if (!item.videoId || seen.has(item.videoId)) {
				return false;
			}
			seen.add(item.videoId);
			return true;
		});
}
//#endregion

export default {
	async fetch(request: Request, env: any): Promise<Response> {
		const url = new URL(request.url);

		//#region handle options
		if (request.method === 'OPTIONS') {
			return new Response(null, { headers: corsHeaders() });
		}
		//#endregion

		/**
		 * By default worker is developemnt mode (WORKER_STRIP_MODE === undefined)
		 * In production mode WORKER_STRIP_MODE === 'production'.
		 */
		const isProdMode = env.WORKER_STRIPE_MODE === 'production';

		//#region ---------- Hello WORLD ----------
		if (!isProdMode && url.pathname === '/') {
			return new Response('Hello world!');
		}
		//#endregion

		//#region ---------- CREATE CHECKOUT SESSION ----------
		if (url.pathname === '/create-checkout-session') {
			if (request.method !== 'POST') {
				return new Response('Method Not Allowed', {
					status: 405,
					headers: corsHeaders(),
				});
			}

			try {
				const body: any = await request.json().catch(() => ({}));
				const { priceId, email, success_url, cancel_url } = body || {};

				if (!priceId || !email || !success_url || !cancel_url) {
					return new Response('Missing params', {
						status: 400,
						headers: corsHeaders(),
					});
				}

				const stripe = new Stripe(env.STRIPE_SECRET_KEY, {
					apiVersion: '2026-02-25.clover',
					httpClient: Stripe.createFetchHttpClient(),
				});

				const session = await stripe.checkout.sessions.create({
					mode: 'payment',
					line_items: [
						{
							price: priceId,
							quantity: 1,
						},
					],
					customer_email: email,

					success_url,
					cancel_url,
				});

				return new Response(
					JSON.stringify({
						url: session.url,
					}),
					{
						headers: {
							'Content-Type': 'application/json',
							...corsHeaders(),
						},
					},
				);
			} catch (err) {
				return new Response(
					JSON.stringify({
						error: (err as Error).message,
					}),
					{
						status: 500,
						headers: {
							'Content-Type': 'application/json',
							...corsHeaders(),
						},
					},
				);
			}
		}
		//#endregion

		//#region ---------- STRIPE WEBHOOK ----------
		if (url.pathname === '/stripe-webhook') {
			if (request.method !== 'POST') {
				return new Response('Method Not Allowed', { status: 405 });
			}

			const rawBody: string = await request.text();

			if (!isProdMode) {
				let rawJson: Partial<TaonStripeCloudflareWorkerData> = {}; // @skipReplaceTaon
				try {
					rawJson = JSON.parse(rawBody);
				} catch {}

				const { productId, clientEmail, stripeSessionId } = rawJson || {};

				if (productId && clientEmail && stripeSessionId) {
					return await saveToDb(env, productId, clientEmail, stripeSessionId);
				}
			}

			const stripe = new Stripe(env.STRIPE_SECRET_KEY, {
				apiVersion: '2026-02-25.clover',
				httpClient: Stripe.createFetchHttpClient(),
			});

			const signature = request.headers.get('stripe-signature');

			let event: Stripe.Event;

			try {
				event = await stripe.webhooks.constructEventAsync(rawBody, signature!, env.STRIPE_WEBHOOK_SECRET);
			} catch (err) {
				return new Response(`Webhook Error: ${(err as Error).message}`, {
					status: 400,
				});
			}

			// ---------- HANDLE CHECKOUT ----------
			if (event.type === 'checkout.session.completed') {
				const session = event.data.object as Stripe.Checkout.Session;

				const stripeSessionId = session.id;
				const clientEmail = session.customer_details?.email;

				if (!clientEmail) {
					return new Response('Missing email', { status: 400 });
				}

				const lineItems = await stripe.checkout.sessions.listLineItems(stripeSessionId, { limit: 1 });

				const productId = lineItems.data[0]?.price?.product as string;

				if (!productId) {
					return new Response('Missing productId', { status: 400 });
				}

				return await saveToDb(env, productId, clientEmail, stripeSessionId);
			}

			return new Response('Event ignored');
		}
		//#endregion

		//#region ---------- CHECK ACCESS ----------
		if (url.pathname === '/check-access') {
			const clientEmail = url.searchParams.get('clientEmail');
			const productId = url.searchParams.get('productId');

			if (!clientEmail || !productId) {
				return new Response('Missing params', { status: 400 });
			}

			const key = `purchase:${clientEmail}:${productId}`;

			const purchase = await env.KV_DATABASE_ONLINE_NAME.get(key);

			return new Response(
				JSON.stringify({
					hasAccess: !!purchase,
				}),
				{
					headers: { 'Content-Type': 'application/json', ...corsHeaders() },
				},
			);
		}
		//#endregion

		//#region ---------- YOUTUBE PLAYLIST VIDEOS ----------
		if (url.pathname === '/youtube-playlist-videos') {
			if (request.method !== 'GET') {
				return new Response('Method Not Allowed', {
					status: 405,
					headers: corsHeaders(),
				});
			}

			try {
				const playlistId = url.searchParams.get('playlistId') || '';

				if (!playlistId) {
					return new Response(
						JSON.stringify({
							error: 'Missing playlistId',
						}),
						{
							status: 400,
							headers: {
								'Content-Type': 'application/json',
								...corsHeaders(),
							},
						},
					);
				}

				const videos = await getYoutubePlaylistVideos(playlistId);

				return new Response(JSON.stringify(videos), {
					headers: {
						'Content-Type': 'application/json',
						...corsHeaders(),
					},
				});
			} catch (err) {
				return new Response(
					JSON.stringify({
						error: (err as Error).message,
					}),
					{
						status: 500,
						headers: {
							'Content-Type': 'application/json',
							...corsHeaders(),
						},
					},
				);
			}
		}
		//#endregion

		return new Response('Not Found', {
			status: 404,
			headers: corsHeaders(),
		});
	},
};
// THIS FILE IS GENERATED BYT TAON - DO NOT MODIFY
