// THIS FILE IS GENERATED BYT TAON - DO NOT MODIFY
import {
  TaonEmailContactPayload,
  TaonEmailContactEnv,
} from '@taon-dev/api-workers/src';

//#region helpers
const JSON_HEADERS = {
  'Content-Type': 'application/json; charset=utf-8',
};

function json(data: unknown, init?: ResponseInit): Response {
  return new Response(JSON.stringify(data), {
    ...init,
    headers: {
      ...JSON_HEADERS,
      ...(init?.headers || {}),
    },
  });
}

function normalizeOrigin(origin: string): string {
  return origin.trim().replace(/\/$/, '');
}

function getAllowedCorsDomains(env: TaonEmailContactEnv): string[] {
  return String(env.CORS_DOMAIN || '')
    .split(',')
    .map(normalizeOrigin)
    .filter(Boolean);
}

function getCorsHeaders(
  request: Request,
  env: TaonEmailContactEnv,
): HeadersInit {
  const origin = normalizeOrigin(request.headers.get('Origin') || '');
  const allowedDomains = getAllowedCorsDomains(env);

  if (allowedDomains.length === 0) {
    return {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'POST, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type',
      'Access-Control-Max-Age': '86400',
    };
  }

  if (allowedDomains.includes(origin)) {
    return {
      'Access-Control-Allow-Origin': origin,
      Vary: 'Origin',
      'Access-Control-Allow-Methods': 'POST, OPTIONS',
      'Access-Control-Allow-Headers':
        request.headers.get('Access-Control-Request-Headers') || 'Content-Type',
      'Access-Control-Max-Age': '86400',
    };
  }

  return {};
}

function isCorsAllowed(request: Request, env: TaonEmailContactEnv): boolean {
  const origin = normalizeOrigin(request.headers.get('Origin') || '');
  const allowedDomains = getAllowedCorsDomains(env);

  if (allowedDomains.length === 0) {
    return true;
  }

  return allowedDomains.includes(origin);
}

function cleanText(value: unknown, maxLength: number): string {
  return String(value || '')
    .replace(/\0/g, '')
    .trim()
    .slice(0, maxLength);
}

function isValidEmail(email: string): boolean {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email) && email.length <= 200;
}

function hasTooManyLinks(message: string): boolean {
  const links = message.match(/https?:\/\//gi) || [];
  return links.length > 2;
}

async function verifyTurnstile(
  token: string,
  request: Request,
  env: TaonEmailContactEnv,
): Promise<boolean> {
  const ip = request.headers.get('CF-Connecting-IP') || '';

  const response = await fetch(
    'https://challenges.cloudflare.com/turnstile/v0/siteverify',
    {
      method: 'POST',
      body: new URLSearchParams({
        secret: env.TURNSTILE_SECRET,
        response: token,
        remoteip: ip,
      }),
    },
  );

  const result = await response.json<{ success: boolean }>();

  return result.success === true;
}

function buildFromHeader(env: TaonEmailContactEnv): string {
  const senderEmail = cleanText(env.SENDER_EMAIL, 200);
  const senderName = cleanText(env.SENDER_NAME || 'Website', 100)
    .replace(/[<>]/g, '')
    .trim();

  if (!senderEmail || !isValidEmail(senderEmail)) {
    throw new Error(
      `Invalid SENDER_EMAIL: "${senderEmail}". Example: contact@website-emails.mattbachata.pl`,
    );
  }

  return `${senderName} <${senderEmail}>`;
}

function escapeHtml(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}

async function sendEmail(params: {
  env: TaonEmailContactEnv;
  name: string;
  email: string;
  message: string;
  ip: string;
}): Promise<void> {
  const { env, name, email, message, ip } = params;

  const subject = `New contact form message from ${name}`;

  const html = `
    <h2>New contact form message</h2>
    <p><strong>Name:</strong> ${escapeHtml(name)}</p>
    <p><strong>Email:</strong> ${escapeHtml(email)}</p>
    <p><strong>IP:</strong> ${escapeHtml(ip)}</p>
    <hr />
    <p style="white-space: pre-line;">${escapeHtml(message)}</p>
  `;

  const text = [
    'New contact form message',
    '',
    `Name: ${name}`,
    `Email: ${email}`,
    `IP: ${ip}`,
    '',
    message,
  ].join('\n');

  const senderEmail = env.SENDER_EMAIL;

  if (!senderEmail) {
    throw new Error(
      'Missing SENDER_EMAIL. It must be a verified sender/domain in Resend.',
    );
  }

  const response = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${env.RESEND_API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      from: buildFromHeader(env),
      to: [env.USER_EMAIL],
      reply_to: email,
      subject,
      html,
      text,
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Resend failed: ${response.status} ${errorText}`);
  }
}
//#endregion

//#region handle request
async function handleRequest(
  request: Request,
  env: TaonEmailContactEnv,
  corsHeaders: HeadersInit,
): Promise<Response> {
  if (request.method === 'OPTIONS') {
    return new Response(null, {
      status: 204,
      headers: corsHeaders,
    });
  }

  if (!isCorsAllowed(request, env)) {
    return json(
      { ok: false, error: 'Origin not allowed' },
      { status: 403, headers: corsHeaders },
    );
  }

  const url = new URL(request.url);

  if (url.pathname !== '/contact') {
    return json(
      { ok: false, error: 'Not found' },
      { status: 404, headers: corsHeaders },
    );
  }

  if (request.method !== 'POST') {
    return json(
      { ok: false, error: 'Method not allowed' },
      { status: 405, headers: corsHeaders },
    );
  }

  let body: TaonEmailContactPayload;

  try {
    body = await request.json<TaonEmailContactPayload>();
  } catch {
    return json(
      { ok: false, error: 'Invalid JSON' },
      { status: 400, headers: corsHeaders },
    );
  }

  // Honeypot: real users should never fill this.
  if (body.website) {
    return json({ ok: true }, { status: 200, headers: corsHeaders });
  }

  const name = cleanText(body.name, 100);
  const email = cleanText(body.email, 200);
  const message = cleanText(body.message, 3000);
  const token = cleanText(body.turnstileToken, 4096);
  const ip = request.headers.get('CF-Connecting-IP') || 'unknown';

  if (!name || !email || !message || !token) {
    return json(
      { ok: false, error: 'Missing required fields' },
      { status: 400, headers: corsHeaders },
    );
  }

  if (!isValidEmail(email)) {
    return json(
      { ok: false, error: 'Invalid email' },
      { status: 400, headers: corsHeaders },
    );
  }

  if (message.length < 10) {
    return json(
      { ok: false, error: 'Message is too short' },
      { status: 400, headers: corsHeaders },
    );
  }

  if (hasTooManyLinks(message)) {
    return json(
      { ok: false, error: 'Too many links' },
      { status: 400, headers: corsHeaders },
    );
  }

  const captchaOk = await verifyTurnstile(token, request, env);

  if (!captchaOk) {
    return json(
      { ok: false, error: 'Captcha validation failed' },
      { status: 403, headers: corsHeaders },
    );
  }

  await sendEmail({
    env,
    name,
    email,
    message,
    ip,
  });

  return json({ ok: true }, { status: 200, headers: corsHeaders });
}
//#endregion

export default {
  async fetch(request: Request, env: TaonEmailContactEnv): Promise<Response> {
    const corsHeaders = getCorsHeaders(request, env);

    try {
      return await handleRequest(request, env, corsHeaders);
    } catch (error) {
      console.error(error);

      return json(
        {
          ok: false,
          error:
            error instanceof Error ? error.message : 'Internal server error',
        },
        { status: 500, headers: corsHeaders },
      );
    }
  },
};
// THIS FILE IS GENERATED BYT TAON - DO NOT MODIFY
