// THIS FILE IS GENERATED BYT TAON - DO NOT MODIFY
import {
  createWorkerAdapter,
  EndpointContext,
  createFakeExpressApp,
} from 'taon/src';

import startFn from '../../../../../../tmp-source-esm-dist/app';
const app = createFakeExpressApp();

startFn({
  overrideExpressApp: app,
}).then(() => {
  // @ts-ignore
  var ContextsEndpointStorageInstance = // @ts-ignore
    globalThis['$$$ContextsEndpointStorage$$$'];

  const endpoints: EndpointContext[] =
    ContextsEndpointStorageInstance.arr || [];
  Promise.all(
    endpoints.map(c => c.initControllersHook(ContextsEndpointStorageInstance)),
  );
  console.log(ContextsEndpointStorageInstance.SPECIAL_APP_READY_MESSAGE);
});

export default {
  fetch: createWorkerAdapter(app),
};
// THIS FILE IS GENERATED BYT TAON - DO NOT MODIFY
